#!/bin/bash
#script for using a graphical dialog to jack_capture. Originally written by Svend-Erik Kjær Madsen

#This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


OPTIONS=$@

if [ ! `which zenity` ] ; then
    echo "zenity needed";
    exit;
fi

while true
do
  zenity  --question --ok-label="Yes" --cancel-label="No" --text="PRESS YES TO START REC"
  case "$?" in
    0) `dirname $0`/jack_capture --no-stdin $OPTIONS &
       some_pid=$!
       zenity --info --text=" RECORDING IN PROGRESS\n PRESS OK TO STOP REC "
       kill -s SIGINT $some_pid
    ;;
    1) exit;
    ;;
  esac
done
